# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_อาจารย์อยาได้อะไรค้าบ'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ที่อยู่',
            field=models.CharField(default='ไม่บอกนะอิอิ', max_length=20),
        ),
    ]
